def main():

    #inputPath = "../Testing_examples/Opsins.aln", "emboss"
    #inputPath = "../Testing_examples/RhoGTP.aln"
    #inputPath = "../Testing_examples/RandomSequence.aln"
    #outputPath = "../testOutput.fasta"
    #includeConservative = True
    #numDropoutsToMake = 0 # Unused for now

    # Read in arguments and return any errors
    if not len(sys.argv) == 5:
        raise Exception("Wrong number of args, should have 4 args but got " + str(len(sys.argv) - 1))

    inputPath = sys.argv[1]
    outputPath = sys.argv[2]
    includeConservatives = sys.argv[3]
    numDropoutsToMake = sys.argv[4]

    if not os.path.exists(inputPath):
        raise FileNotFoundError(inputPath + " doesn't exist")
    if (not includeConservatives == "y") and (not includeConservatives == "n"):
        raise ValueError("Argument for whether or not to include conservative substitutions isn't y or n")
    try:
        numDropoutsToMake = int(numDropoutsToMake)
    except:
        raise TypeError("Argument for number of dropouts isn't an integer")
    
    if not os.path.exists(outputPath):
        os.makedirs(outputPath)


    # Read in the sequences and names from the provided alignment file
    try:
        alignment = AlignIO.read(inputPath, "emboss")
    except:
        raise Exception("There was an error reading the alignment input file")
    
    nameFirst = alignment[0].description
    nameSecond = alignment[1].description
    alignFirst = str(alignment[0].seq)
    alignSecond = str(alignment[1].seq)

    position = 0
    aaPosition = 1 # Specifically refers to the first sequence
    mutationList = []
    # Make mutation list
    while position < len(alignFirst):
        charFirst = alignFirst[position]
        charSecond = alignSecond[position]
        # If there is a difference
        if not charFirst == charSecond:
            # If it's a missense
            if (not charFirst == "-") and (not charSecond == "-"):
                mutationName = charFirst + str(aaPosition) + charSecond
                if isConservative(charFirst, charSecond):
                    mutationType = "cons_missense"
                else:
                    mutationType= "noncons_missense"
                mutationList.append([mutationName, mutationType, aaPosition])

            # If it's an insertion in the second sequence relative to the first
            elif charFirst == "-":
                mutationName = "insertion" + str(aaPosition) + charSecond
                mutationType = "insertion"
                mutationList.append([mutationName, mutationType, aaPosition])
                aaPosition = aaPosition - 1

            # If it's a deletion in the second sequence relative to the first
            elif charSecond == "-": 
                mutationName = "deletion" + str(aaPosition) + charFirst
                mutationType = "deletion"
                mutationList.append([mutationName, mutationType, aaPosition])
        position = position + 1
        aaPosition = aaPosition + 1
        

    #print(mutationList)
    # Create a fasta file starting with the two input reference sequences
    seqFirstTemplate = alignFirst.replace("-", "")
    seqSecond = alignSecond.replace("-", "")
    with open(outputPath, "w") as output:
        output.write(">first_ref_" + nameFirst + "\n")
        output.write(seqFirstTemplate + "\n\n")
        output.write(">second_ref_" + nameSecond + "\n")
        output.write(seqSecond + "\n\n")
    # Add dropouts containing only one mutation each
    for mutation in mutationList:
        mutationName = mutation[0]
        mutationType = mutation[1]
        mutationIndex = mutation[2] - 1
        if mutationType == "cons_missense" and includeConservatives == "n":
            continue
        elif "missense" in mutationType:
            newAA = mutationName[-1]
            dropoutSequence = seqFirstTemplate[:mutationIndex] + newAA + seqFirstTemplate[mutationIndex + 1:]
        elif mutationType == "insertion":
            newAA = mutationName[-1]
            dropoutSequence = seqFirstTemplate[:mutationIndex] + newAA + seqFirstTemplate[mutationIndex:]            
        elif mutationType == "deletion":

            dropoutSequence = seqFirstTemplate[:mutationIndex] + seqFirstTemplate[mutationIndex + 1:]

        i = 1
        with open(outputPath, "a") as output:
            output.write(">dropout" + str(i) + "_" + mutationName + "\n")
            output.write(dropoutSequence + "\n\n")
            i = i + 1


# Function to check if a subtitution is conservative given two residues, generated by ChatGPT
def isConservative(aaOne, aaTwo): 
    aaCategories = {
    "nonpolar": {"A", "V", "L", "I", "M", "P", "G"},
    "aromatic": {"Y", "F", "W"},
    "polar_uncharged": {"S", "T", "N", "Q"},
    "positively_charged": {"K", "R", "H"},
    "negatively_charged": {"D", "E"},
    "special": {"C"}  # glycine often treated separately
    }

    for aaSet in aaCategories.values():
        if (aaOne in aaSet) and (aaTwo in aaSet):
            return True

    return False


if __name__ == "__main__":
    from Bio import SeqIO, AlignIO #type: ignore
    import sys
    import os
    main()
    
