# Form implementation generated from reading ui file 'NMThesisGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets #type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 650)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1100, 600))
        self.tabWidget.setObjectName("tabWidget")

#######################################################
            
        self.CombinedTab = QtWidgets.QWidget()
        self.CombinedTab.setObjectName("CombinedTab")

        self.InputTypeOne = QtWidgets.QRadioButton(parent=self.CombinedTab)
        self.InputTypeOne.setEnabled(True)
        self.InputTypeOne.setGeometry(QtCore.QRect(10, 20, 191, 20))
        #self.InputTypeOne.setAutoExclusive(True)
        self.InputTypeOne.setObjectName("InputTypeOne")
        self.InputTypeOne.setHidden(True)

        self.InputTypeTwo = QtWidgets.QRadioButton(parent=self.CombinedTab)
        self.InputTypeTwo.setGeometry(QtCore.QRect(10, 190, 201, 20))
        #self.InputTypeTwo.setAutoExclusive(True)
        self.InputTypeTwo.setObjectName("InputTypeTwo")
        self.InputTypeTwo.setChecked(True)
        self.InputTypeTwo.setHidden(True)

        self.CombinedButtonGroup = QtWidgets.QButtonGroup(parent=self.centralwidget)
        self.CombinedButtonGroup.setObjectName("CombinedButtonGroup")
        self.CombinedButtonGroup.addButton(self.InputTypeOne)
        self.CombinedButtonGroup.addButton(self.InputTypeTwo)



        self.UniIDBox = QtWidgets.QGroupBox(parent=self.CombinedTab)
        self.UniIDBox.setGeometry(QtCore.QRect(40, 50, 201, 80))
        self.UniIDBox.setObjectName("UniIDBox")
        self.UniIDBox.setHidden(True)

        self.UniIDInputOne = QtWidgets.QLineEdit(parent=self.UniIDBox)
        self.UniIDInputOne.setGeometry(QtCore.QRect(60, 20, 113, 21))
        self.UniIDInputOne.setText("")
        self.UniIDInputOne.setObjectName("UniIDInputOne")
        self.UniIDInputOne.setHidden(True)

        self.UniIDInputTwo = QtWidgets.QLineEdit(parent=self.UniIDBox)
        self.UniIDInputTwo.setGeometry(QtCore.QRect(60, 50, 113, 21))
        self.UniIDInputTwo.setText("")
        self.UniIDInputTwo.setObjectName("UniIDInputTwo")
        self.UniIDInputTwo.setHidden(True)

        self.UniIDLabelOne = QtWidgets.QLabel(parent=self.UniIDBox)
        self.UniIDLabelOne.setGeometry(QtCore.QRect(20, 20, 27, 16))
        self.UniIDLabelOne.setObjectName("UniIDLabelOne")
        self.UniIDLabelOne.setHidden(True)

        self.UniIDLabelTwo = QtWidgets.QLabel(parent=self.UniIDBox)
        self.UniIDLabelTwo.setGeometry(QtCore.QRect(10, 50, 46, 16))
        self.UniIDLabelTwo.setObjectName("UniIDLabelTwo")
        self.UniIDLabelTwo.setHidden(True)



        self.UniRefoldCheck = QtWidgets.QCheckBox(parent=self.CombinedTab)
        self.UniRefoldCheck.setGeometry(QtCore.QRect(40, 140, 211, 20))
        self.UniRefoldCheck.setObjectName("UniRefoldCheck")
        self.UniRefoldCheck.setHidden(True)
        self.UniRefoldCheck.setChecked(True)



        self.InputFileLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.InputFileLabel.setGeometry(QtCore.QRect(40, 220, 111, 21))
        self.InputFileLabel.setObjectName("InputFileLabel")

        self.InputFileEntry = QtWidgets.QLineEdit(parent=self.CombinedTab)
        self.InputFileEntry.setGeometry(QtCore.QRect(100, 220, 261, 21))
        self.InputFileEntry.setObjectName("InputFileEntry")



        self.SequencesBox = QtWidgets.QGroupBox(parent=self.CombinedTab)
        self.SequencesBox.setGeometry(QtCore.QRect(40, 370, 141, 151))
        self.SequencesBox.setObjectName("SequencesBox")
        self.SequencesBox.setHidden(True)

        #self.SequencesLabelOne = QtWidgets.QLabel(parent=self.HeadersBox)
        #self.SequencesLabelOne.setGeometry(QtCore.QRect(5, 69, 10, 21))
        #self.SequencesLabelOne.setObjectName("SequencesLabelOne")

        #self.SequencesLabelTwo = QtWidgets.QLabel(parent=self.HeadersBox)
        #self.SequencesLabelTwo.setGeometry(QtCore.QRect(5, 109, 9, 21))
        #self.SequencesLabelTwo.setObjectName("SequencesLabelTwo")

        #self.SequencesInputOne = QtWidgets.QLineEdit(parent=self.HeadersBox)
        #self.SequencesInputOne.setGeometry(QtCore.QRect(20, 70, 113, 21))
        #self.SequencesInputOne.setText("1")
        #self.SequencesInputOne.setObjectName("SequencesInputOne")

        #self.SequencesInputTwo = QtWidgets.QLineEdit(parent=self.HeadersBox)
        #self.SequencesInputTwo.setGeometry(QtCore.QRect(20, 110, 113, 21))
        #self.SequencesInputTwo.setText("2")
        #self.SequencesInputTwo.setObjectName("SequencesInputTwo")



        self.ConservativesCheck = QtWidgets.QCheckBox(parent=self.CombinedTab)
        self.ConservativesCheck.setGeometry(QtCore.QRect(540, 160, 211, 20))
        self.ConservativesCheck.setObjectName("ConservativesCheck")

        self.TemplatesCheck = QtWidgets.QCheckBox(parent=self.CombinedTab)
        self.TemplatesCheck.setGeometry(QtCore.QRect(540, 190, 171, 20))
        self.TemplatesCheck.setObjectName("TemplatesCheck")

        self.RelaxCheck = QtWidgets.QCheckBox(parent=self.CombinedTab)
        self.RelaxCheck.setGeometry(QtCore.QRect(540, 220, 181, 20))
        self.RelaxCheck.setChecked(True)
        self.RelaxCheck.setObjectName("RelaxCheck")




        self.DropoutNumLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.DropoutNumLabel.setGeometry(QtCore.QRect(430, 80, 191, 21))
        self.DropoutNumLabel.setObjectName("DropoutNumLabel")
        self.DropoutNumLabel.setHidden(True)

        self.DropoutNumInput = QtWidgets.QLineEdit(parent=self.CombinedTab)
        self.DropoutNumInput.setGeometry(QtCore.QRect(610, 80, 113, 21))
        self.DropoutNumInput.setObjectName("DropoutNumInput")
        self.DropoutNumInput.setHidden(True)

        self.RecyclesLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.RecyclesLabel.setGeometry(QtCore.QRect(480, 120, 141, 21))
        self.RecyclesLabel.setObjectName("RecyclesLabel")

        self.RecyclesInput = QtWidgets.QLineEdit(parent=self.CombinedTab)
        self.RecyclesInput.setGeometry(QtCore.QRect(610, 120, 113, 21))
        self.RecyclesInput.setObjectName("RecyclesInput")



        self.ChimeraPathLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.ChimeraPathLabel.setGeometry(QtCore.QRect(540, 260, 141, 21))
        self.ChimeraPathLabel.setObjectName("ChimeraPathLabel")

        self.ChimeraPathEntry = QtWidgets.QLineEdit(parent=self.CombinedTab)
        self.ChimeraPathEntry.setGeometry(QtCore.QRect(430, 280, 351, 21))
        self.ChimeraPathEntry.setObjectName("ChimeraPathEntry")



        self.AlignAlgoBox = QtWidgets.QGroupBox(parent=self.CombinedTab)
        self.AlignAlgoBox.setGeometry(QtCore.QRect(750, 80, 331, 91))
        self.AlignAlgoBox.setObjectName("AlignAlgoBox")

        self.MatchmakeButton = QtWidgets.QRadioButton(parent=self.AlignAlgoBox)
        self.MatchmakeButton.setGeometry(QtCore.QRect(20, 30, 301, 20))
        self.MatchmakeButton.setChecked(True)
        self.MatchmakeButton.setAutoExclusive(True)
        self.MatchmakeButton.setObjectName("MatchmakeButton")

        self.AlignButton = QtWidgets.QRadioButton(parent=self.AlignAlgoBox)
        self.AlignButton.setEnabled(True)
        self.AlignButton.setGeometry(QtCore.QRect(20, 60, 161, 20))
        self.AlignButton.setChecked(False)
        self.AlignButton.setAutoExclusive(True)
        self.AlignButton.setObjectName("AlignButton")

        self.SameLengthCheck = QtWidgets.QCheckBox(parent=self.CombinedTab)
        self.SameLengthCheck.setGeometry(QtCore.QRect(780, 190, 191, 20))
        self.SameLengthCheck.setChecked(True)
        self.SameLengthCheck.setObjectName("SameLengthCheck")



        self.OutputLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.OutputLabel.setGeometry(QtCore.QRect(435, 300, 80, 21))
        self.OutputLabel.setObjectName("OutputLabel")

        self.OutputEntry = QtWidgets.QLineEdit(parent=self.CombinedTab)
        self.OutputEntry.setGeometry(QtCore.QRect(520, 300, 261, 21))
        self.OutputEntry.setObjectName("OutputEntry")



        self.errorMessageLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.errorMessageLabel.setGeometry(QtCore.QRect(400, 370, 341, 20))
        self.errorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.errorMessageLabel.setHidden(True)
        self.errorMessageLabel.setStyleSheet("color: red;")

        self.StatusLabel = QtWidgets.QLabel(parent=self.CombinedTab)
        self.StatusLabel.setGeometry(QtCore.QRect(470, 430, 271, 16))
        self.StatusLabel.setObjectName("StatusLabel")
        self.StatusLabel.setHidden(True)

        self.RunButton = QtWidgets.QPushButton(parent=self.CombinedTab)
        self.RunButton.setGeometry(QtCore.QRect(510, 400, 121, 32))
        self.RunButton.setObjectName("RunButton")
        self.RunButton.clicked.connect(self.combinedFunction)


        self.tabWidget.addTab(self.CombinedTab, "")    

#######################################################


        self.ShuffleTab = QtWidgets.QWidget()
        self.ShuffleTab.setObjectName("ShuffleTab")



        self.SInputTypeOne = QtWidgets.QRadioButton(parent=self.ShuffleTab)
        self.SInputTypeOne.setEnabled(True)
        self.SInputTypeOne.setGeometry(QtCore.QRect(10, 20, 191, 20))
        #self.SInputTypeOne.setAutoExclusive(True)
        self.SInputTypeOne.setObjectName("SInputTypeOne")
        self.SInputTypeOne.setHidden(True)

        self.SInputTypeTwo = QtWidgets.QRadioButton(parent=self.ShuffleTab)
        self.SInputTypeTwo.setEnabled(True)
        self.SInputTypeTwo.setGeometry(QtCore.QRect(10, 190, 201, 20))
        self.SInputTypeTwo.setChecked(True)
        #self.SInputTypeTwo.setAutoExclusive(True)
        self.SInputTypeTwo.setObjectName("SInputTypeTwo")
        self.SInputTypeTwo.setHidden(True)

        self.ShuffleButtonGroup = QtWidgets.QButtonGroup(parent=self.centralwidget)
        self.ShuffleButtonGroup.setObjectName("ShuffleButtonGroup")
        self.ShuffleButtonGroup.addButton(self.SInputTypeOne)
        self.ShuffleButtonGroup.addButton(self.SInputTypeTwo)



        self.SUniIDBox = QtWidgets.QGroupBox(parent=self.ShuffleTab)
        self.SUniIDBox.setGeometry(QtCore.QRect(40, 50, 201, 80))
        self.SUniIDBox.setObjectName("SUniIDBox")
        self.SUniIDBox.setHidden(True)

        self.SUniIDLabelOne = QtWidgets.QLabel(parent=self.SUniIDBox)
        self.SUniIDLabelOne.setGeometry(QtCore.QRect(20, 20, 27, 16))
        self.SUniIDLabelOne.setObjectName("SUniIDLabelOne")
        self.SUniIDLabelOne.setHidden(True)

        self.SUniIDLabelTwo = QtWidgets.QLabel(parent=self.SUniIDBox)
        self.SUniIDLabelTwo.setGeometry(QtCore.QRect(10, 50, 46, 16))
        self.SUniIDLabelTwo.setObjectName("SUniIDLabelTwo")
        self.SUniIDLabelTwo.setHidden(True)

        self.SUniIDInputOne = QtWidgets.QLineEdit(parent=self.SUniIDBox)
        self.SUniIDInputOne.setGeometry(QtCore.QRect(60, 20, 113, 21))
        self.SUniIDInputOne.setText("")
        self.SUniIDInputOne.setObjectName("SUniIDInputOne")
        self.SUniIDInputOne.setHidden(True)

        self.SUniIDInputTwo = QtWidgets.QLineEdit(parent=self.SUniIDBox)
        self.SUniIDInputTwo.setGeometry(QtCore.QRect(60, 50, 113, 21))
        self.SUniIDInputTwo.setText("")
        self.SUniIDInputTwo.setObjectName("SUniIDInputTwo")
        self.SUniIDInputTwo.setHidden(True)



        self.SInputFileLabel = QtWidgets.QLabel(parent=self.ShuffleTab)
        self.SInputFileLabel.setGeometry(QtCore.QRect(40, 220, 111, 21))
        self.SInputFileLabel.setObjectName("SInputFileLabel")

        self.SInputFileEntry = QtWidgets.QLineEdit(parent=self.ShuffleTab)
        self.SInputFileEntry.setGeometry(QtCore.QRect(100, 220, 261, 21))
        self.SInputFileEntry.setObjectName("SInputFileEntry")




        self.SSequencesBox = QtWidgets.QGroupBox(parent=self.ShuffleTab)
        self.SSequencesBox.setGeometry(QtCore.QRect(40, 370, 141, 151))
        self.SSequencesBox.setObjectName("SSequencesBox")
        self.SSequencesBox.setHidden(True)

        #self.SSequencesLabelOne = QtWidgets.QLabel(parent=self.SHeadersBox)
        #self.SSequencesLabelOne.setGeometry(QtCore.QRect(5, 69, 10, 21))
        #self.SSequencesLabelOne.setObjectName("SSequencesLabelOne")

        #self.SSequencesLabelTwo = QtWidgets.QLabel(parent=self.SHeadersBox)
        #self.SSequencesLabelTwo.setGeometry(QtCore.QRect(5, 109, 9, 21))
        #self.SSequencesLabelTwo.setObjectName("SSequencesLabelTwo")

        #self.SSequencesInputOne = QtWidgets.QLineEdit(parent=self.SHeadersBox)
        #self.SSequencesInputOne.setGeometry(QtCore.QRect(20, 70, 113, 21))
        #self.SSequencesInputOne.setText("1")
        #self.SSequencesInputOne.setObjectName("SSequencesInputOne")

        #self.SSequencesInputTwo = QtWidgets.QLineEdit(parent=self.SHeadersBox)
        #self.SSequencesInputTwo.setGeometry(QtCore.QRect(20, 110, 113, 21))
        #self.SSequencesInputTwo.setText("2")
        #self.SSequencesInputTwo.setObjectName("SSequencesInputTwo")



        self.SConservativesCheck = QtWidgets.QCheckBox(parent=self.ShuffleTab)
        self.SConservativesCheck.setGeometry(QtCore.QRect(540, 70, 211, 20))
        self.SConservativesCheck.setObjectName("SConservativesCheck")



        self.SDropoutNumLabel = QtWidgets.QLabel(parent=self.ShuffleTab)
        self.SDropoutNumLabel.setGeometry(QtCore.QRect(485, 180, 141, 21))
        self.SDropoutNumLabel.setObjectName("SDropoutNumLabel")
        self.SDropoutNumLabel.setHidden(True)

        self.SDropoutNumInput = QtWidgets.QLineEdit(parent=self.ShuffleTab)
        self.SDropoutNumInput.setGeometry(QtCore.QRect(610, 180, 113, 21))
        self.SDropoutNumInput.setObjectName("SDropoutNumInput")
        self.SDropoutNumInput.setHidden(True)



        self.SOutputLabel = QtWidgets.QLabel(parent=self.ShuffleTab)
        self.SOutputLabel.setGeometry(QtCore.QRect(410, 300, 110, 21))
        self.SOutputLabel.setObjectName("SOutputLabel")

        self.SOutputEntry = QtWidgets.QLineEdit(parent=self.ShuffleTab)
        self.SOutputEntry.setGeometry(QtCore.QRect(520, 300, 261, 21))
        self.SOutputEntry.setObjectName("SOutputEntry")



        self.SRunButton = QtWidgets.QPushButton(parent=self.ShuffleTab)
        self.SRunButton.setGeometry(QtCore.QRect(510, 400, 121, 32))
        self.SRunButton.setObjectName("SRunButton")
        self.SRunButton.clicked.connect(self.shufflePanelFunction)

        self.SerrorMessageLabel = QtWidgets.QLabel(parent=self.ShuffleTab)
        self.SerrorMessageLabel.setGeometry(QtCore.QRect(400, 370, 341, 20))
        self.SerrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SerrorMessageLabel.setObjectName("SerrorMessageLabel")
        self.SerrorMessageLabel.setHidden(True)
        self.SerrorMessageLabel.setStyleSheet("color: red;")

        self.SStatusLabel = QtWidgets.QLabel(parent=self.ShuffleTab)
        self.SStatusLabel.setGeometry(QtCore.QRect(470, 430, 291, 16))
        self.SStatusLabel.setObjectName("SStatusLabel")
        self.SStatusLabel.setHidden(True)



        self.tabWidget.addTab(self.ShuffleTab, "")

#####################################################################

        self.FoldTab = QtWidgets.QWidget()
        self.FoldTab.setObjectName("FoldTab")



        self.FRefFoldCheck = QtWidgets.QCheckBox(parent=self.FoldTab)
        self.FRefFoldCheck.setGeometry(QtCore.QRect(50, 320, 171, 20))
        self.FRefFoldCheck.setChecked(True)
        self.FRefFoldCheck.setObjectName("FRefFoldCheck")
        self.FRefFoldCheck.setHidden(True)

        self.FTemplatesCheck = QtWidgets.QCheckBox(parent=self.FoldTab)
        self.FTemplatesCheck.setGeometry(QtCore.QRect(540, 70, 171, 20))
        self.FTemplatesCheck.setObjectName("FTemplatesCheck")

        self.FRelaxCheck = QtWidgets.QCheckBox(parent=self.FoldTab)
        self.FRelaxCheck.setGeometry(QtCore.QRect(540, 120, 181, 20))
        self.FRelaxCheck.setChecked(True)
        self.FRelaxCheck.setObjectName("FRelaxCheck")



        self.FDropoutNumLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FDropoutNumLabel.setGeometry(QtCore.QRect(30, 240, 241, 20))
        self.FDropoutNumLabel.setObjectName("FDropoutNumLabel")
        self.FDropoutNumLabel.setHidden(True)

        self.FDropoutNumLabel_2 = QtWidgets.QLabel(parent=self.FoldTab)
        self.FDropoutNumLabel_2.setGeometry(QtCore.QRect(10, 260, 251, 20))
        self.FDropoutNumLabel_2.setObjectName("FDropoutNumLabel_2")
        self.FDropoutNumLabel_2.setHidden(True)

        self.FDropoutNumLabel_3 = QtWidgets.QLabel(parent=self.FoldTab)
        self.FDropoutNumLabel_3.setGeometry(QtCore.QRect(60, 280, 71, 20))
        self.FDropoutNumLabel_3.setObjectName("FDropoutNumLabel_3")
        self.FDropoutNumLabel_3.setHidden(True)

        self.FDropoutNumInput = QtWidgets.QLineEdit(parent=self.FoldTab)
        self.FDropoutNumInput.setGeometry(QtCore.QRect(140, 240, 113, 21))
        self.FDropoutNumInput.setText("")
        self.FDropoutNumInput.setObjectName("FDropoutNumInput")
        self.FDropoutNumInput.setHidden(True)

        self.FRecyclesLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FRecyclesLabel.setGeometry(QtCore.QRect(480, 180, 141, 20))
        self.FRecyclesLabel.setObjectName("FRecyclesLabel")

        self.FRecyclesInput = QtWidgets.QLineEdit(parent=self.FoldTab)
        self.FRecyclesInput.setGeometry(QtCore.QRect(610, 180, 113, 21))
        self.FRecyclesInput.setObjectName("FRecyclesInput")



        self.FInputFileLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FInputFileLabel.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.FInputFileLabel.setObjectName("FInputFileLabel")

        self.FInputFileEntry = QtWidgets.QLineEdit(parent=self.FoldTab)
        self.FInputFileEntry.setGeometry(QtCore.QRect(80, 90, 261, 21))
        self.FInputFileEntry.setObjectName("FInputFileEntry")

        self.FOutputLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FOutputLabel.setGeometry(QtCore.QRect(435, 300, 121, 21))
        self.FOutputLabel.setObjectName("FOutputLabel")

        self.FOutputEntry = QtWidgets.QLineEdit(parent=self.FoldTab)
        self.FOutputEntry.setGeometry(QtCore.QRect(520, 300, 261, 21))
        self.FOutputEntry.setObjectName("FOutputEntry")



        self.FRunButton = QtWidgets.QPushButton(parent=self.FoldTab)
        self.FRunButton.setGeometry(QtCore.QRect(510, 400, 121, 32))
        self.FRunButton.setObjectName("FRunButton")
        self.FRunButton.clicked.connect(self.foldingPanelFunction)

        self.FerrorMessageLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FerrorMessageLabel.setGeometry(QtCore.QRect(400, 370, 341, 20))
        self.FerrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FerrorMessageLabel.setObjectName("FerrorMessageLabel")
        self.FerrorMessageLabel.setHidden(True)
        self.FerrorMessageLabel.setStyleSheet("color: red;")

        self.FStatusLabel = QtWidgets.QLabel(parent=self.FoldTab)
        self.FStatusLabel.setGeometry(QtCore.QRect(470, 430, 301, 16))
        self.FStatusLabel.setObjectName("FStatusLabel")
        self.FStatusLabel.setHidden(True)



        self.tabWidget.addTab(self.FoldTab, "")

#############################################################


        self.AnalyzeTab = QtWidgets.QWidget()
        self.AnalyzeTab.setObjectName("AnalyzeTab")



        self.ARefButtonOne = QtWidgets.QRadioButton(parent=self.AnalyzeTab)
        self.ARefButtonOne.setEnabled(True)
        self.ARefButtonOne.setGeometry(QtCore.QRect(10, 240, 191, 20))
        self.ARefButtonOne.setAutoExclusive(True)
        self.ARefButtonOne.setObjectName("ARefButtonOne")
        self.ARefButtonOne.setHidden(True)

        self.ARefButtonTwo = QtWidgets.QRadioButton(parent=self.AnalyzeTab)
        self.ARefButtonTwo.setGeometry(QtCore.QRect(10, 380, 151, 20))
        self.ARefButtonTwo.setChecked(True)
        self.ARefButtonTwo.setAutoExclusive(True)
        self.ARefButtonTwo.setObjectName("ARefButtonTwo")
        self.ARefButtonTwo.setHidden(True)


        self.AUniIDBox = QtWidgets.QGroupBox(parent=self.AnalyzeTab)
        self.AUniIDBox.setGeometry(QtCore.QRect(40, 270, 201, 80))
        self.AUniIDBox.setObjectName("AUniIDBox")
        self.AUniIDBox.setHidden(True)

        self.AUniIDLabelOne = QtWidgets.QLabel(parent=self.AUniIDBox)
        self.AUniIDLabelOne.setGeometry(QtCore.QRect(20, 20, 27, 16))
        self.AUniIDLabelOne.setObjectName("AUniIDLabelOne")
        self.AUniIDLabelOne.setHidden(True)

        self.AUniIDLabelTwo = QtWidgets.QLabel(parent=self.AUniIDBox)
        self.AUniIDLabelTwo.setGeometry(QtCore.QRect(10, 50, 46, 16))
        self.AUniIDLabelTwo.setObjectName("AUniIDLabelTwo")
        self.AUniIDLabelTwo.setHidden(True)

        self.AUniIDInputOne = QtWidgets.QLineEdit(parent=self.AUniIDBox)
        self.AUniIDInputOne.setGeometry(QtCore.QRect(60, 20, 113, 21))
        self.AUniIDInputOne.setText("")
        self.AUniIDInputOne.setObjectName("AUniIDInputOne")
        self.AUniIDInputOne.setHidden(True)

        self.AUniIDInputTwo = QtWidgets.QLineEdit(parent=self.AUniIDBox)
        self.AUniIDInputTwo.setGeometry(QtCore.QRect(60, 50, 113, 21))
        self.AUniIDInputTwo.setText("")
        self.AUniIDInputTwo.setObjectName("AUniIDInputTwo")
        self.AUniIDInputTwo.setHidden(True)

        #self.AHeadersLabelZero = QtWidgets.QLabel(parent=self.AnalyzeTab)
        #self.AHeadersLabelZero.setGeometry(QtCore.QRect(10, 380, 151, 20))
        #self.AHeadersLabelZero.setObjectNames("AHeadersLabelZero")

        #self.AHeadersLabelOne = QtWidgets.QLabel(parent=self.AnalyzeTab)
        #self.AHeadersLabelOne.setGeometry(QtCore.QRect(20, 419, 10, 21))
        #self.AHeadersLabelOne.setObjectName("AHeadersLabelOne")

        #self.AHeadersLabelTwo = QtWidgets.QLabel(parent=self.AnalyzeTab)
        #self.AHeadersLabelTwo.setGeometry(QtCore.QRect(20, 459, 9, 21))
        #self.AHeadersLabelTwo.setObjectName("AHeadersLabelTwo")

        #self.AHeadersInputOne = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        #self.AHeadersInputOne.setGeometry(QtCore.QRect(40, 420, 113, 21))
        #self.AHeadersInputOne.setText("")
        #self.AHeadersInputOne.setObjectName("AHeadersInputOne")

        #self.AHeadersInputTwo = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        #self.AHeadersInputTwo.setGeometry(QtCore.QRect(40, 460, 113, 21))
        #self.AHeadersInputTwo.setText("")
        #self.AHeadersInputTwo.setObjectName("AHeadersInputTwo")



        self.AShuffleNumLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AShuffleNumLabel.setGeometry(QtCore.QRect(50, 170, 50, 16))
        self.AShuffleNumLabel.setObjectName("AShuffleNumLabel")
        self.AShuffleNumLabel.setHidden(True)

        self.AShuffleNumLabel_2 = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AShuffleNumLabel_2.setGeometry(QtCore.QRect(10, 190, 251, 20))
        self.AShuffleNumLabel_2.setObjectName("AShuffleNumLabel_2")
        self.AShuffleNumLabel_2.setHidden(True)

        self.AShuffleNumInput = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        self.AShuffleNumInput.setGeometry(QtCore.QRect(120, 170, 113, 21))
        self.AShuffleNumInput.setText("0")
        self.AShuffleNumInput.setObjectName("AShuffleNumInput")
        self.AShuffleNumInput.setHidden(True)



        self.AInputFolderLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AInputFolderLabel.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.AInputFolderLabel.setObjectName("AInputFolderLabel")

        self.AInputFolderLabel_2 = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AInputFolderLabel_2.setGeometry(QtCore.QRect(60, 125, 291, 16))
        self.AInputFolderLabel_2.setObjectName("AInputFolderLabel_2")

        self.AInputFolderEntry = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        self.AInputFolderEntry.setGeometry(QtCore.QRect(110, 100, 261, 21))
        self.AInputFolderEntry.setObjectName("AInputFolderEntry")



        self.AAlignAlgoBox = QtWidgets.QGroupBox(parent=self.AnalyzeTab)
        self.AAlignAlgoBox.setGeometry(QtCore.QRect(420, 70, 331, 91))
        self.AAlignAlgoBox.setObjectName("AAlignAlgoBox")

        self.AMatchmakeButton = QtWidgets.QRadioButton(parent=self.AAlignAlgoBox)
        self.AMatchmakeButton.setGeometry(QtCore.QRect(20, 30, 301, 20))
        self.AMatchmakeButton.setChecked(True)
        self.AMatchmakeButton.setAutoExclusive(True)
        self.AMatchmakeButton.setObjectName("AMatchmakeButton")

        self.AAlignButton = QtWidgets.QRadioButton(parent=self.AAlignAlgoBox)
        self.AAlignButton.setEnabled(True)
        self.AAlignButton.setGeometry(QtCore.QRect(20, 60, 161, 20))
        self.AAlignButton.setChecked(False)
        self.AAlignButton.setAutoExclusive(True)
        self.AAlignButton.setObjectName("AAlignButton")

        self.ASameLengthCheck = QtWidgets.QCheckBox(parent=self.AnalyzeTab)
        self.ASameLengthCheck.setGeometry(QtCore.QRect(430, 170, 191, 20))
        self.ASameLengthCheck.setChecked(True)
        self.ASameLengthCheck.setObjectName("ASameLengthCheck")



        #self.AOutputLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        #self.AOutputLabel.setGeometry(QtCore.QRect(435, 300, 121, 21))
        #self.AOutputLabel.setObjectName("AOutputLabel")

        #self.AOutputEntry = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        #self.AOutputEntry.setGeometry(QtCore.QRect(520, 300, 261, 21))
        #self.AOutputEntry.setObjectName("AOutputEntry")



        self.AChimeraPathLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AChimeraPathLabel.setGeometry(QtCore.QRect(540, 260, 141, 21))
        self.AChimeraPathLabel.setObjectName("AChimeraPathLabel")

        self.AChimeraPathEntry = QtWidgets.QLineEdit(parent=self.AnalyzeTab)
        self.AChimeraPathEntry.setGeometry(QtCore.QRect(430, 280, 351, 21))
        self.AChimeraPathEntry.setObjectName("AChimeraPathEntry")



        self.ARunButton = QtWidgets.QPushButton(parent=self.AnalyzeTab)
        self.ARunButton.setGeometry(QtCore.QRect(510, 400, 121, 32))
        self.ARunButton.setObjectName("ARunButton")
        self.ARunButton.clicked.connect(self.analyzePanelFunction)

        self.AerrorMessageLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AerrorMessageLabel.setGeometry(QtCore.QRect(400, 370, 341, 20))
        self.AerrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AerrorMessageLabel.setObjectName("AerrorMessageLabel")
        self.AerrorMessageLabel.setHidden(True)
        self.AerrorMessageLabel.setStyleSheet("color: red;")

        self.AStatusLabel = QtWidgets.QLabel(parent=self.AnalyzeTab)
        self.AStatusLabel.setGeometry(QtCore.QRect(470, 430, 241, 16))
        self.AStatusLabel.setObjectName("AStatusLabel")
        self.AStatusLabel.setHidden(True)



        self.tabWidget.addTab(self.AnalyzeTab, "")


############################################################





        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        currentFolder = sys.path[0] + "/"
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputTypeOne.setText(_translate("MainWindow", "Uniprot entries"))
        self.InputTypeTwo.setText(_translate("MainWindow", "Alignment file"))
        self.SequencesBox.setTitle(_translate("MainWindow", "Select sequences in alignment file"))
        #self.SequencesLabelOne.setText(_translate("MainWindow", "Ref"))
        #self.SequencesLabelTwo.setText(_translate("MainWindow", "Mutated"))
        self.AlignAlgoBox.setTitle(_translate("MainWindow", "Choose structure alignment algorithim"))
        self.AAlignAlgoBox.setTitle(_translate("MainWindow", "Choose structure alignment algorithim"))
        self.MatchmakeButton.setText(_translate("MainWindow", "Matchmake (required for different length refs)"))
        self.SameLengthCheck.setText(_translate("MainWindow", "Refs are the same length"))
        self.AMatchmakeButton.setText(_translate("MainWindow", "Matchmake (required for different length refs)"))
        self.ASameLengthCheck.setText(_translate("MainWindow", "Refs are the same length"))
        self.AlignButton.setText(_translate("MainWindow", "Align (more accurate)"))
        self.AAlignButton.setText(_translate("MainWindow", "Align (more accurate)"))
        self.errorMessageLabel.setText(_translate("MainWindow", "Error Message"))
        self.UniIDBox.setTitle(_translate("MainWindow", "Enter Uniprot IDs"))
        self.UniIDLabelOne.setText(_translate("MainWindow", "First"))
        self.UniIDLabelTwo.setText(_translate("MainWindow", "Second"))
        self.StatusLabel.setText(_translate("MainWindow", "Status"))
        self.ConservativesCheck.setText(_translate("MainWindow", "Include conservative substitutions"))
        self.DropoutNumLabel.setText(_translate("MainWindow", "Number of top dropouts to use"))
        self.DropoutNumInput.setText(_translate("MainWindow", "5"))
        self.RecyclesLabel.setText(_translate("MainWindow", "Number of recycles"))
        self.RecyclesInput.setText(_translate("MainWindow", "3"))
        self.TemplatesCheck.setText(_translate("MainWindow", "Use templates"))
        self.RelaxCheck.setText(_translate("MainWindow", "Use relaxation"))
        self.InputFileLabel.setText(_translate("MainWindow", "Input file"))
        self.InputFileEntry.setText(_translate("MainWindow", currentFolder))
        self.OutputEntry.setText(_translate("MainWindow", currentFolder))
        self.OutputLabel.setText(_translate("MainWindow", "Output folder"))
        self.RunButton.setText(_translate("MainWindow", "Run"))
        self.UniRefoldCheck.setText(_translate("MainWindow", "Refold references"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CombinedTab), _translate("MainWindow", "Combined"))
        self.SSequencesBox.setTitle(_translate("MainWindow", "Select sequences in alignment file"))
        #self.SSequencesLabelOne.setText(_translate("MainWindow", "Ref"))
        #self.SSequencesLabelTwo.setText(_translate("MainWindow", "Mutated"))
        #self.AHeadersLabelZero.setText(_translate("MainWindow", "Provide references"))
        #self.AHeadersLabelOne.setText(_translate("MainWindow", "Ref"))
        #self.AHeadersLabelTwo.setText(_translate("MainWindow", "Muatated"))
        self.SInputTypeTwo.setText(_translate("MainWindow", "Alignment file"))
        self.SInputFileLabel.setText(_translate("MainWindow", "Input file"))
        self.SInputFileEntry.setText(_translate("MainWindow", currentFolder))
        self.SUniIDBox.setTitle(_translate("MainWindow", "Enter Uniprot IDs"))
        self.SUniIDLabelOne.setText(_translate("MainWindow", "First"))
        self.SUniIDLabelTwo.setText(_translate("MainWindow", "Second"))
        self.SInputTypeOne.setText(_translate("MainWindow", "Uniprot entries"))
        self.SConservativesCheck.setText(_translate("MainWindow", "Include conservative substitutions"))
        self.SDropoutNumLabel.setText(_translate("MainWindow", "Number of top dropouts to use"))
        self.SDropoutNumInput.setText(_translate("MainWindow", "5"))
        self.SOutputLabel.setText(_translate("MainWindow", "Output filename:"))
        self.SOutputEntry.setText(_translate("MainWindow", os.path.join(currentFolder, "shuffles.fasta")))
        self.SRunButton.setText(_translate("MainWindow", "Run shuffler"))
        self.SerrorMessageLabel.setText(_translate("MainWindow", "Error Message"))
        self.SStatusLabel.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ShuffleTab), _translate("MainWindow", "Shuffle"))
        self.FDropoutNumLabel.setText(_translate("MainWindow", "Shuffles to fold"))
        self.FRecyclesLabel.setText(_translate("MainWindow", "Number of recycles"))
        self.FRecyclesInput.setText(_translate("MainWindow", "3"))
        self.FTemplatesCheck.setText(_translate("MainWindow", "Use templates"))
        self.FRelaxCheck.setText(_translate("MainWindow", "Use relaxation"))
        self.FDropoutNumLabel_2.setText(_translate("MainWindow", "(not counting 2 references)"))
        self.FDropoutNumLabel_3.setText(_translate("MainWindow", "(max 10)"))
        self.FInputFileLabel.setText(_translate("MainWindow", "Input file"))
        self.FInputFileEntry.setText(_translate("MainWindow", currentFolder))
        self.FOutputLabel.setText(_translate("MainWindow", "Output folder"))
        self.FOutputEntry.setText(_translate("MainWindow", currentFolder))
        self.FRunButton.setText(_translate("MainWindow", "Run AlphaFold"))
        self.FerrorMessageLabel.setText(_translate("MainWindow", "Error Message"))
        self.FStatusLabel.setText(_translate("MainWindow", "Status"))
        self.FRefFoldCheck.setText(_translate("MainWindow", "Fold 2 references"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FoldTab), _translate("MainWindow", "Fold"))
        self.AInputFolderLabel.setText(_translate("MainWindow", "Input folder"))
        self.AInputFolderLabel_2.setText(_translate("MainWindow", "(will override any previous analysis outputs)"))
        self.AInputFolderEntry.setText(_translate("MainWindow", currentFolder))
        self.AShuffleNumLabel.setText(_translate("MainWindow", "Shuffles"))
        self.AShuffleNumLabel_2.setText(_translate("MainWindow", "(not counting 2 references)"))
        self.ARefButtonOne.setText(_translate("MainWindow", "Uniprot entries"))
        self.ARefButtonTwo.setText(_translate("MainWindow", "Present in folder"))
        #self.AOutputLabel.setText(_translate("MainWindow", "Output folder"))
        #self.AOutputEntry.setText(_translate("MainWindow", currentFolder))
        self.ARunButton.setText(_translate("MainWindow", "Run analysis"))
        self.AerrorMessageLabel.setText(_translate("MainWindow", "Error Message"))
        self.AStatusLabel.setText(_translate("MainWindow", "Status"))
        self.AUniIDBox.setTitle(_translate("MainWindow", "Enter Uniprot IDs"))
        self.AUniIDLabelOne.setText(_translate("MainWindow", "First"))
        self.AUniIDLabelTwo.setText(_translate("MainWindow", "Second"))
        self.ChimeraPathLabel.setText(_translate("MainWindow", "ChimeraX exe path"))
        self.ChimeraPathEntry.setText(_translate("MainWindow", "/lib/ucsf-chimerax/bin/ChimeraX"))
        self.AChimeraPathLabel.setText(_translate("MainWindow", "ChimeraX exe path"))
        self.AChimeraPathEntry.setText(_translate("MainWindow", "/lib/ucsf-chimerax/bin/ChimeraX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AnalyzeTab), _translate("MainWindow", "Analyze"))

    def combinedFunction(self):
        self.errorMessageLabel.setHidden(True)
        self.StatusLabel.setHidden(True)

        # If the user specified output folder doesn't exist, create it
        outputFolder = self.OutputEntry.text()
        if not os.path.exists(outputFolder):
            os.makedirs(outputFolder)

        # Set the location for the file that will be created in the first step
        dropoutsPath = os.path.join(outputFolder, "dropouts.fasta")
        
        # Set the number of dropouts to be created, a value of 0 or no provided value will indicate to make a dropout for every mutation
        dropoutCount = self.DropoutNumInput.text()
        if dropoutCount == "":
            dropoutCount == 0
        if not dropoutCount.isdigit():
            self.errorMessageLabel.setText("Dropout number contains non-numeric characters")
            self.errorMessageLabel.setHidden(False)
            return
        dropoutCount = int(dropoutCount)
        #if dropoutCount > 10:
        #    self.errorMessageLabel.setText("Too many dropouts")
        #    self.errorMessageLabel.setHidden(False)
        #    return

        # Define the variable for whether conservative mutations should be included when creating the dropout sequences
        if self.ConservativesCheck.isChecked():
            useConservatives = "y"
        else:
            useConservatives = "n"

        # If uniprot is selected as input method (CURRENTLY UNUSED)
        if self.CombinedButtonGroup.checkedId() == -2:
            uniIDOne = self.UniIDInputOne.text()
            uniIDTwo = self.UniIDInputTwo.text()
            firstUniEntry = getUniprot(uniIDOne)
            if firstUniEntry == "error":
                self.errorMessageLabel.setText("Could not fetch sequence for first uniprot ID")
                self.errorMessageLabel.setHidden(False)
                return

            secondUniEntry = getUniprot(uniIDTwo)
            if secondUniEntry == "error":
                self.errorMessageLabel.setText("Could not fetch sequence for second uniprot ID")
                self.errorMessageLabel.setHidden(False)
                return
            with open(dropoutsPath, "w") as output:
                output.write(firstUniEntry[0])
                output.write("\n")
                output.write(firstUniEntry[1])
                output.write("\n")
                output.write(secondUniEntry[0])
                output.write("\n")
                output.write(secondUniEntry[1])





            inputFilePath = dropoutsPath
        # If alignment file is selected as input method, check to ensure the file exists
        elif self.CombinedButtonGroup.checkedId() == -3:

            foldRefs = "y"
            uniIDOne = "NA"
            uniIDTwo = "NA"

            inputFilePath = self.InputFileEntry.text()
            if not os.path.exists(inputFilePath):
                self.errorMessageLabel.setText("Input alignment file doesn't exist")
                self.errorMessageLabel.setHidden(False)
                return

        if self.UniRefoldCheck.isChecked():
            useUniStructures = False
        else:
            useUniStructures = True
        
        # Check that the number of recycles given is valid
        numRecycles = self.RecyclesInput.text()
        if not numRecycles.isdigit():
            self.errorMessageLabel.setText("Number of recycles contains non-numeric characters")
            self.errorMessageLabel.setHidden(False)
            return
        
        # Check that the provided ChimeraX is correct
        cxPath = self.ChimeraPathEntry.text()
        if not os.path.exists(cxPath):
                self.errorMessageLabel.setText("ChimeraX path doesn't exist")
                self.errorMessageLabel.setHidden(False)
                return

        # Define the variable for which ChimeraX function should be used for structure alignment
        if self.MatchmakeButton.isChecked():
            alignFunction = "mm"
        elif self.AlignButton.isChecked():
            alignFunction = "a"

        # Read user input for whether the provided reference sequences are the same length
        if self.SameLengthCheck.isChecked():
            areSameLength = "y"
        else:
            areSameLength = "n"


        if areSameLength == "n" and alignFunction == "a":
            self.errorMessageLabel.setText("Align function was chosen but refs aren't same length")
            self.errorMessageLabel.setHidden(False)
            return

        # Call the script to generate dropouts
        dropoutCommand = ["python", "Dropout_generator.py", inputFilePath, dropoutsPath, useConservatives, str(dropoutCount)]
        os.system(" ".join(dropoutCommand))

        self.StatusLabel.setText("Dropouts generated")
        self.StatusLabel.setHidden(False)

        # Define the variables for whether colabfold should use templates and relaxation
        if self.TemplatesCheck.isChecked():
            useTemplates = "y"
        else:
            useTemplates = "n"
        if self.RelaxCheck.isChecked():
            useRelaxation = "y"
        else:
            useRelaxation = "n"

        #foldingStatus = foldShuffles(shufflesPath, outputFolder, not useUniStructures, shuffleCount, numRecycles, useTemplates, useRelaxation, self.StatusLabel)
        #if not foldingStatus == "none":
        #    self.errorMessageLabel.setText(foldingStatus)
        #    self.errorMessageLabel.setHidden(False)
        #    return
            
        # Call the script for using local colab fold to predict structures
        foldingCommand = ["python", "local_colab_script.py", dropoutsPath, outputFolder, foldRefs, numRecycles, useTemplates, useRelaxation]
        os.system(" ".join(foldingCommand))
        
        self.StatusLabel.setText("Analyzing folds")

        

        # Create a settings file for the chimerax script to read
        with open("cxScriptSettings.txt", "w") as toWrite:
            toWrite.write(outputFolder + "\n")
            #toWrite.write(str(shuffleCount) + "\n")
            toWrite.write(alignFunction + "\n")
            toWrite.write(areSameLength + "\n")
            if useUniStructures:
                toWrite.write("y\n")
                toWrite.write(uniIDOne + "\n")
                toWrite.write(uniIDTwo)
            else:
                toWrite.write("n\n")
                toWrite.write("NA")
                toWrite.write("NA")

        # Call the chimerax script
        thisPath = sys.path[0]
        os.system(cxPath + " " + os.path.join(thisPath, "chimeraxScript.py"))
        #os.remove("cxScriptSettings.txt")
        self.StatusLabel.setText("Finished")

        
    def shufflePanelFunction(self):
        self.SerrorMessageLabel.setHidden(True)
        self.SStatusLabel.setHidden(True)


        
        # Set the number of dropouts to be created, a value of 0 or no provided value will indicate to make a dropout for every mutation
        dropoutCount = self.SDropoutNumInput.text()
        if dropoutCount == "":
            dropoutCount == 0
        if not dropoutCount.isdigit():
            self.SerrorMessageLabel.setText("Shuffle number contains non-numeric characters")
            self.SerrorMessageLabel.setHidden(False)
            return
        dropoutCount = int(dropoutCount)

        # Define the variable for whether conservative mutations should be included when creating the dropout sequences
        if self.SConservativesCheck.isChecked():
            useConservatives = "y"
        else:
            useConservatives = "n"

        # If uniprot is selected as input method (CURRENTLY UNUSED)
        if self.ShuffleButtonGroup.checkedId() == -2:
            uniIDOne = self.SUniIDInputOne.text()
            uniIDTwo = self.SUniIDInputTwo.text()
            firstUniEntry = getUniprot(uniIDOne)
            if firstUniEntry == "error":
                self.SerrorMessageLabel.setText("Could not fetch sequence for first uniprot ID")
                self.SerrorMessageLabel.setHidden(False)
                return

            secondUniEntry = getUniprot(uniIDTwo)
            if secondUniEntry == "error":
                self.SerrorMessageLabel.setText("Could not fetch sequence for second uniprot ID")
                self.SerrorMessageLabel.setHidden(False)
                return
            #with open(dropoutsPath, "w") as output:
            #    output.write(firstUniEntry[0])
            #    output.write("\n")
            #    output.write(firstUniEntry[1])
            #    output.write("\n")
            #    output.write(secondUniEntry[0])
            #    output.write("\n")
            #    output.write(secondUniEntry[1])


            #inputFilePath = dropoutsPath
        # If fasta file is selected as input method, check to ensure the file exists
        elif self.ShuffleButtonGroup.checkedId() == -3:
            inputFilePath = self.SInputFileEntry.text()
            if not os.path.exists(inputFilePath):
                self.SerrorMessageLabel.setText("Input file doesn't exist")
                self.SerrorMessageLabel.setHidden(False)
                return

        # If the user specified output folder doesn't exist, create it
        dropoutsPath = self.SOutputEntry.text()
        if not os.path.exists(os.path.dirname(dropoutsPath)):
            os.makedirs(os.path.dirname(dropoutsPath))

        # Call the script to generate dropouts
        dropoutCommand = ["python", "Dropout_generator.py", inputFilePath, dropoutsPath, useConservatives, str(dropoutCount)]
        os.system(" ".join(dropoutCommand))

        self.SStatusLabel.setText("Shuffling complete")   
        self.SStatusLabel.setHidden(False)     

    def foldingPanelFunction(self):
        self.FerrorMessageLabel.setHidden(True)
        self.FStatusLabel.setHidden(True)

        # If the user specified output folder doesn't exist, create it
        outputFolder = self.FOutputEntry.text()
        if not os.path.exists(outputFolder):
            os.makedirs(outputFolder)

        # Check to make sure that the provided input path exists
        inputFilePath = self.FInputFileEntry.text()
        if not os.path.exists(inputFilePath):
            self.FerrorMessageLabel.setText("Input file doesn't exist")
            self.FerrorMessageLabel.setHidden(False)
            return
        
        # Define the variables for whether colabfold should use templates and relaxation
        if self.FTemplatesCheck.isChecked():
            useTemplates = "y"
        else:
            useTemplates = "n"
        if self.FRelaxCheck.isChecked():
            useRelaxation = "y"
        else:
            useRelaxation = "n"

        # Currently unused
        if self.FRefFoldCheck.isChecked():
            shouldFoldRefs = "y"
        else:
            shouldFoldRefs = "n"

        # Currently unused
        dropoutCount = self.FDropoutNumInput.text()
        if dropoutCount == "":
            dropoutCount == 0
        if not dropoutCount.isdigit():
            self.FerrorMessageLabel.setText("Dropout number contains non-numeric characters")
            self.FerrorMessageLabel.setHidden(False)
            return
        dropoutCount = int(dropoutCount)
        #if dropoutCount > 10:
        #    self.FerrorMessageLabel.setText("Too many shuffles")
        #    self.FerrorMessageLabel.setHidden(False)
        #    return

        # Check that the recycles number provided is valid
        numRecycles = self.FRecyclesInput.text()
        if not numRecycles.isdigit():
            self.FerrorMessageLabel.setText("Number of recycles contains non-numeric characters")
            self.FerrorMessageLabel.setHidden(False)
            return

        #foldingStatus = foldShuffles(inputFilePath, outputFolder, shouldFoldRefs, shuffleCount, numRecycles, useTemplates, useRelaxation, self.FStatusLabel)

        #if not foldingStatus == "none":
        #    self.FerrorMessageLabel.setText(foldingStatus)
        #    self.FerrorMessageLabel.setHidden(False)
        #    return

        # Call the script to use local colab fold for structure prediction
        foldingCommand = ["python", "local_colab_script.py", inputFilePath, outputFolder, shouldFoldRefs, numRecycles, useTemplates, useRelaxation]
        os.system(" ".join(foldingCommand))
        
        self.FStatusLabel.setText("Finished folding")
        
    def analyzePanelFunction(self):
        self.AerrorMessageLabel.setHidden(True)
        self.AStatusLabel.setHidden(True)

        # Check that the input path provided is valid
        inputFolderPath = self.AInputFolderEntry.text()
        if not os.path.exists(inputFolderPath):
            self.AerrorMessageLabel.setText("Input folder doesn't exist")
            self.AerrorMessageLabel.setHidden(False)
            return

        # Currently unused
        shuffleCount = self.AShuffleNumInput.text()
        if not shuffleCount.isdigit():
            self.AerrorMessageLabel.setText("Shuffle number contains non-numeric characters")
            self.AerrorMessageLabel.setHidden(False)
            return

        # Currently unused (button two always on)
        if self.ARefButtonOne.isChecked():
            refSource = "y"
            uniIDOne = self.AUniIDInputOne.text()
            uniIDOne = uniIDOne.replace(" ", "")
            uniIDTwo = self.AUniIDInputTwo.text()
            uniIDTwo = uniIDTwo.replace(" ", "")
        elif self.ARefButtonTwo.isChecked():
            refSource = "n"
            uniIDOne = "NA"
            uniIDTwo = "NA"
        
        # Check that path to the ChimeraX program is valid
        cxPath = self.AChimeraPathEntry.text()
        if not os.path.exists(cxPath):
            self.AerrorMessageLabel.setText("ChimeraX path doesn't exist")
            self.AerrorMessageLabel.setHidden(False)
            return

        if self.AMatchmakeButton.isChecked():
            alignFunction = "mm"
        elif self.AAlignButton.isChecked():
            alignFunction = "a"

        if self.ASameLengthCheck.isChecked():
            areSameLength = "y"
        else:
            areSameLength = "n"

        if areSameLength == "n" and alignFunction == "a":
            self.AerrorMessageLabel.setText("Align function was chosen but refs aren't same length")
            self.AerrorMessageLabel.setHidden(False)
            return
        
        with open("cxScriptSettings.txt", "w") as toWrite:
            toWrite.write(inputFolderPath + "\n")
            toWrite.write(alignFunction + "\n")
            toWrite.write(areSameLength + "\n")
            toWrite.write(refSource + "\n")
            toWrite.write(uniIDOne + "\n")
            toWrite.write(uniIDTwo)

        thisPath = sys.path[0]
        os.system(cxPath + " " + os.path.join(thisPath, "chimeraxScript.py"))
        os.remove("cxScriptSettings.txt")

        self.AStatusLabel.setText("Finished")
        self.AStatusLabel.setHidden(False)


# Function to return the name and sequence given a uniprot ID (currently unused)
def getUniprot(ID):
    url = f"https://rest.uniprot.org/uniprotkb/{ID}.fasta"
    response = requests.get(url)

    if response.status_code == 200:
        fastaData = response.text
        fastaData =  fastaData.split("\n", 1)
        headerLine = fastaData[0]
        headerLine = headerLine.split(" ")
        headerLine = headerLine[0].replace("|", "_")
        toReturn = [headerLine, fastaData[1]]
        return toReturn
    else:
        return "error"







if __name__ == "__main__":
    import sys
    import os
    import requests #type: ignore
    from Bio import SeqIO #type: ignore
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
